name: Ubuntu2004-R

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -la  ${{github.workspace}}

      - name: Install deps
        run: sudo apt install -y swig autoconf automake build-essential dirmngr gnupg apt-transport-https ca-certificates software-properties-common
      - name: CRAN R
        run: |
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
          apt install r-base

      - name: Configure
        run: |
          cd ${{github.workspace}}
          ./autogen.sh
          ./configure --without-mpi

      - name: Build
        run: |
          make r

      - uses: actions/upload-artifact@v2
        with:
          name: Rsomoclu
          path: ${{github.workspace}}/src/Rsomoclu_*.tar.gz
