name: Ubuntu2004

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -la  ${{github.workspace}}

      - name: Install deps
        run: sudo apt install -y swig autoconf automake build-essential python3-pip python3-numpy

      - name: Configure
        run: |
          cd ${{github.workspace}}
          ./autogen.sh
          ./configure --without-mpi

      - name: Build
        run: |
          make
          make python3_wheel
          ls -la  ${{github.workspace}}/src/Python/dist/

      - uses: actions/upload-artifact@v2
        with:
          name: libsomoclu.so
          path: ${{github.workspace}}/src/libsomoclu.so
      - uses: actions/upload-artifact@v2
        with:
          name: python_dist_wheel
          path: ${{github.workspace}}/src/Python/dist/
